package com.medistock.shared.domain.notification

/**
 * Types of notifications that can be generated by the system.
 * Some are triggered by pg_cron (server-side), others are local-only.
 */
enum class NotificationType {
    /** Product has expired (expiry_date < now). Triggered by pg_cron. */
    PRODUCT_EXPIRED,

    /** Product is expiring soon (within 7 days). Triggered by pg_cron. */
    PRODUCT_EXPIRING_SOON,

    /** Product stock is below minimum threshold. Triggered by pg_cron. */
    LOW_STOCK,

    /** Sync has failed (local only - not from pg_cron). */
    SYNC_FAILED,

    /** There are pending changes to sync (local only - not from pg_cron). */
    SYNC_PENDING
}

/**
 * Priority levels for notifications.
 * Affects display order and visual treatment.
 */
enum class NotificationPriority {
    LOW,
    MEDIUM,
    HIGH,
    CRITICAL;

    companion object {
        fun fromString(value: String): NotificationPriority {
            return entries.find { it.name.equals(value, ignoreCase = true) } ?: MEDIUM
        }
    }
}

/**
 * Represents a notification event.
 * Can be synced from Supabase or created locally.
 */
data class NotificationEvent(
    /** Unique identifier (UUID from Supabase or local). */
    val id: String,

    /** Type of notification. */
    val type: NotificationType,

    /** Priority level. */
    val priority: NotificationPriority,

    /** Notification title (short, displayed in notification header). */
    val title: String,

    /** Notification message body. */
    val message: String,

    /** ID of the referenced entity (product_id, batch_id, etc.). */
    val referenceId: String? = null,

    /** Type of the referenced entity ('product', 'batch', etc.). */
    val referenceType: String? = null,

    /** Site ID for filtering (optional). */
    val siteId: String? = null,

    /** Deep link for navigation when notification is tapped. */
    val deepLink: String? = null,

    /** Creation timestamp (epoch milliseconds). */
    val createdAt: Long,

    /** Whether this notification has been displayed to the user. */
    val isDisplayed: Boolean = false,

    /** Whether the user has dismissed/acknowledged this notification. */
    val isDismissed: Boolean = false
) {
    companion object {
        /**
         * Create a notification from SQLDelight query result.
         */
        fun fromDatabase(
            id: String,
            type: String,
            priority: String,
            title: String,
            message: String,
            referenceId: String?,
            referenceType: String?,
            siteId: String?,
            deepLink: String?,
            createdAt: Long,
            isDisplayed: Long,
            isDismissed: Long
        ): NotificationEvent {
            return NotificationEvent(
                id = id,
                type = NotificationType.entries.find { it.name == type } ?: NotificationType.SYNC_PENDING,
                priority = NotificationPriority.fromString(priority),
                title = title,
                message = message,
                referenceId = referenceId,
                referenceType = referenceType,
                siteId = siteId,
                deepLink = deepLink,
                createdAt = createdAt,
                isDisplayed = isDisplayed == 1L,
                isDismissed = isDismissed == 1L
            )
        }
    }
}

/**
 * User preferences for notifications.
 * Stored locally and optionally synced to Supabase.
 */
data class NotificationPreferences(
    /** Enable expiration alerts. */
    val expiryAlertEnabled: Boolean = true,

    /** Days before expiry to trigger alert. */
    val expiryDaysThreshold: Int = 30,

    /** Enable low stock alerts. */
    val lowStockAlertEnabled: Boolean = true,

    /** Enable sync failure notifications. */
    val syncFailedEnabled: Boolean = true,

    /** Start of quiet hours (format: "HH:mm", e.g., "22:00"). */
    val quietHoursStart: String? = "22:00",

    /** End of quiet hours (format: "HH:mm", e.g., "07:00"). */
    val quietHoursEnd: String? = "07:00",

    /** Enable notification sounds. */
    val soundEnabled: Boolean = true
)
